#k8s集群主机清单（3 master + 2 worker)

[k8s_cluster:children]
master
worker

[master]
k8s_master01 ansible_host=10.0.1.31
k8s_master02 ansible_host=10.0.1.32
k8s_master03 ansible_host=10.0.1.33

[worker]
k8s_node01 ansible_host=10.0.1.41 k8s-node01=10.0.1.41
k8s_node02 ansible_host=10.0.1.42 k8s-node02=10.0.1.42

[k8s_cluster:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'  #首次连接时，跳过主机指纹确认
ansible_port=22
